language: python
python:
  - "3.4"
  - "3.5"

install: 
  pip install -r requirements-test.txt
script: 
  - py.test --doctest-modules aptdetector tests
  - coverage run --source aptdetector -m py.test
after_success:
  coveralls
